home:
    path:     /
    defaults: { _controller: NoxLogicAppBundle:Default:index }

user_settings:
    path:     /settings
    defaults: { _controller: NoxLogicAppBundle:User:settings }

user:
    path:     /user:{user}
    defaults: { _controller: NoxLogicAppBundle:User:index }

user_new_repo:
    path:     "/user:{user}/new"
    defaults: { _controller: NoxLogicAppBundle:User:newRepository }

repo:
    path:     "/user:{user}/repo:{repo}"
    defaults: { _controller: NoxLogicAppBundle:Repo:index }

repo_tree:
    path:     "/user:{user}/repo:{repo}/tree:{tree}/path:{path}"
    defaults: { _controller: NoxLogicAppBundle:Repo:tree }
    requirements: { "path": ".+" }

repo_tree_view:
    path:     "/user:{user}/repo:{repo}/tree:{tree}/path:{path}/view"
    defaults: { _controller: NoxLogicAppBundle:Repo:view }
    requirements: { "path": ".+" }
