home:
    path:     /
    defaults: { _controller: NoxLogicAppBundle:Default:index }

user_settings:
    path:     /settings
    defaults: { _controller: NoxLogicAppBundle:User:settings }

user_settings_sshkey_ajax:
    path:     /settings/ssh/_ajax
    defaults: { _controller: NoxLogicAppBundle:User:sshkeyAjax }

user:
    path:     /user:{user}
    defaults: { _controller: NoxLogicAppBundle:User:index }

user_new_repo:
    path:     "/user:{user}/new"
    defaults: { _controller: NoxLogicAppBundle:User:newRepository }

repo:
    path:     "/repo:{user}/{repo}"
    defaults: { _controller: NoxLogicAppBundle:Repo:index }

repo_contributors:
    path:     "/repo:{user}/{repo}/contributors"
    defaults: { _controller: NoxLogicAppBundle:Repo:contributors }

repo_contributors_ajax:
    path:     "/_ajax/repo:{user}/{repo}/contributors/{offset}"
    defaults: { _controller: NoxLogicAppBundle:Repo:contributorsAjax }

# repo_blob_view must be before repo_tree, otherwise, 'view:' will be seen as the path
repo_blob_view:
    path:     "/repo:{user}/{repo}/blob:{tree}{path}"
    defaults: { _controller: NoxLogicAppBundle:Repo:blob }
    requirements: { "path": ".*" }

repo_tree:
    path:     "/repo:{user}/{repo}/tree:{tree}{path}"
    defaults: { _controller: NoxLogicAppBundle:Repo:tree }
    requirements: { "path": ".*" }
